apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: python=faruk67/my-python-k8s-app
    argocd-image-updater.argoproj.io/python.update-strategy: newest-build
    argocd-image-updater.argoproj.io/python.allow-tags: regexp:^([a-f0-9]{40})$
    argocd-image-updater.argoproj.io/python.helm.image-tag: image.tag
spec:
  project: default

  source:
    repoURL: https://github.com/faruk56-arch/python-k8-simple-app
    targetRevision: main
    path: helm/python-app
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

